"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertCircle,ArrowLeft,Check,ChevronDown,Copy,Gamepad2,Headphones,Menu,MessageCircle,Minus,Plus,Search,ShieldCheck,ShoppingBag,Sparkles,User,X,Zap } from "lucide-react";

const APP_BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const games=[
 {name:"Mobile Legends",studio:"MOONTON",tag:"ML",color:"#38bdf8",icon:"⚔️"},{name:"Free Fire",studio:"GARENA",tag:"FF",color:"#ff7a18",icon:"🔥"},{name:"Valorant",studio:"RIOT GAMES",tag:"VAL",color:"#ff4655",icon:"◢"},{name:"Genshin Impact",studio:"HOYOVERSE",tag:"GI",color:"#8b8dff",icon:"✦"},{name:"PUBG Mobile",studio:"KRAFTON",tag:"PUBG",color:"#f5b942",icon:"🎯"},{name:"Honkai: Star Rail",studio:"HOYOVERSE",tag:"HSR",color:"#b782ff",icon:"✧"},{name:"Call of Duty M",studio:"ACTIVISION",tag:"COD",color:"#dde539",icon:"⌖"},{name:"Roblox",studio:"ROBLOX CORP.",tag:"RBX",color:"#dbdbdb",icon:"◇"},
];
const packs=[{amount:"86 Diamonds",bonus:"+8 bonus",price:20000},{amount:"172 Diamonds",bonus:"+17 bonus",price:39000,hot:true},{amount:"257 Diamonds",bonus:"+26 bonus",price:57000},{amount:"344 Diamonds",bonus:"+34 bonus",price:76000},{amount:"706 Diamonds",bonus:"+70 bonus",price:151000,best:true},{amount:"Weekly Pass",bonus:"7 hari",price:29000}];
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
type DemoOrder={id:string;game:string;package:string;playerId:string;server:string;payment:string;total:number;status:string;createdAt:string;createdTs:number};
export default function Home(){
 const[query,setQuery]=useState("");const[activeGame,setActiveGame]=useState(games[0]);const[selectedPack,setSelectedPack]=useState(1);const[payment,setPayment]=useState("QRIS");const[qty,setQty]=useState(1);const[more,setMore]=useState(false);const[userId,setUserId]=useState("");const[server,setServer]=useState("");const[error,setError]=useState(false);const[success,setSuccess]=useState(false);const[isGamePage,setIsGamePage]=useState(false);const[isCheckPage,setIsCheckPage]=useState(false);const[isAboutPage,setIsAboutPage]=useState(false);const[isFaqPage,setIsFaqPage]=useState(false);const[paymentOpen,setPaymentOpen]=useState(false);const[orderId,setOrderId]=useState("");const[checkId,setCheckId]=useState("");const[checkedOrder,setCheckedOrder]=useState<DemoOrder|null|undefined>(undefined);const[mobileOpen,setMobileOpen]=useState(false);const[history,setHistory]=useState<DemoOrder[]>([]);const[loginOpen,setLoginOpen]=useState(false);const[userName,setUserName]=useState("");const[loginName,setLoginName]=useState("");const[faqOpen,setFaqOpen]=useState(0);const[navigating,setNavigating]=useState<typeof games[number]|null>(null);const[processingPayment,setProcessingPayment]=useState(false);
 const[gameMissing,setGameMissing]=useState(false);const[copied,setCopied]=useState(false);
 const shownGames=useMemo(()=>games.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())).slice(0,more?8:6),[query,more]);const total=packs[selectedPack].price*qty;
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const requested=params.get("game");const match=games.find(g=>g.name===requested);if(match){setActiveGame(match);setIsGamePage(true);document.title=`Top Up ${match.name} — PixelPay`}else if(requested){setGameMissing(true);document.title="Game Tidak Ditemukan — PixelPay"}else if(params.get("view")==="check"){setIsCheckPage(true);document.title="Cek Transaksi — PixelPay"}else if(params.get("view")==="about"){setIsAboutPage(true);document.title="Tentang Project — PixelPay"}else if(params.get("view")==="faq"){setIsFaqPage(true);document.title="FAQ — PixelPay"}const orders:DemoOrder[]=JSON.parse(localStorage.getItem("pixelpay_orders")||"[]");setHistory(orders);setUserName(localStorage.getItem("pixelpay_user")||"")},[]);
 const order=(game=activeGame)=>{setActiveGame(game);document.getElementById("topup")?.scrollIntoView({behavior:"smooth"})};
 const openGamePage=(game:typeof games[number])=>{if(navigating)return;setNavigating(game);setTimeout(()=>{window.location.href=`${APP_BASE}/?game=${encodeURIComponent(game.name)}#topup`},650)};
 const checkout=()=>{if(userId.length<6||server.length<3){setError(true);return}setPaymentOpen(true)};
 const completePayment=()=>{if(processingPayment)return;setProcessingPayment(true);setTimeout(()=>{const now=Date.now();const id=`PX-${now.toString().slice(-8)}`;const saved:DemoOrder={id,game:activeGame.name,package:packs[selectedPack].amount,playerId:userId,server,payment,total,status:"Sedang Diproses",createdAt:new Date().toLocaleString("id-ID"),createdTs:now};const orders:DemoOrder[]=JSON.parse(localStorage.getItem("pixelpay_orders")||"[]");const next=[saved,...orders].slice(0,20);localStorage.setItem("pixelpay_orders",JSON.stringify(next));setHistory(next);setOrderId(id);setPaymentOpen(false);setProcessingPayment(false);setSuccess(true)},1400)};
 const freshOrders=()=>{const orders:DemoOrder[]=JSON.parse(localStorage.getItem("pixelpay_orders")||"[]");const updated=orders.map(o=>({...o,status:Date.now()-(o.createdTs||0)>8000?"Berhasil":o.status}));localStorage.setItem("pixelpay_orders",JSON.stringify(updated));setHistory(updated);return updated};
 const findOrder=()=>{const orders=freshOrders();setCheckedOrder(orders.find(o=>o.id.toLowerCase()===checkId.trim().toLowerCase())||null)};
 const selectHistory=(o:DemoOrder)=>{setCheckId(o.id);setCheckedOrder({...o,status:Date.now()-(o.createdTs||0)>8000?"Berhasil":o.status});window.scrollTo({top:0,behavior:"smooth"})};
 const login=()=>{if(!loginName.trim())return;localStorage.setItem("pixelpay_user",loginName.trim());setUserName(loginName.trim());setLoginOpen(false)};
 const resetOrder=()=>{setSuccess(false);setUserId("");setServer("");setQty(1);setSelectedPack(1);document.getElementById("topup")?.scrollIntoView({behavior:"smooth"})};
 useEffect(()=>{const notify=(event:MouseEvent)=>{if((event.target as HTMLElement).closest('[aria-label="Salin nomor order"]')){setCopied(true);setTimeout(()=>setCopied(false),2200)}};document.addEventListener("click",notify);return()=>document.removeEventListener("click",notify)},[]);
 return <main>
  {gameMissing&&<div className="game-missing"><AlertCircle size={16}/><span>Game tidak ditemukan. Menampilkan katalog yang tersedia.</span></div>}
  {copied&&<div className="copy-toast" role="status"><Check size={17}/> Nomor order berhasil disalin</div>}
  <a className="wa-contact" href="https://wa.me/6282289985919" target="_blank" rel="noreferrer" aria-label="Hubungi WhatsApp"><MessageCircle size={19}/><span>0822 89** **19</span></a>
  {isAboutPage&&<a className="github-profile" href="https://github.com/megasekarl16-png" target="_blank" rel="noreferrer"><b>GH</b> github.com/megasekarl16-png</a>}
  <nav className="nav wrap"><a className="brand" href={`${APP_BASE}/`}><span className="brand-mark"><Gamepad2 size={20}/></span><span>PIXEL<span>PAY</span></span></a><div className="search"><Search size={18}/><input aria-label="Cari game" placeholder="Cari game..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="nav-links"><a href={`${APP_BASE}/`}>Top Up</a><a href={`${APP_BASE}/?view=check`}>Cek Transaksi</a><a href={`${APP_BASE}/?view=about`}>Tentang Project</a><a href={`${APP_BASE}/?view=faq`}>FAQ</a></div><button className="login profile-trigger" onClick={()=>setLoginOpen(true)}>{userName?<><span>{userName.slice(0,1).toUpperCase()}</span>{userName}</>:<>Masuk</>}</button><button className="menu" onClick={()=>setMobileOpen(!mobileOpen)} aria-expanded={mobileOpen} aria-controls="mobile-menu" aria-label={mobileOpen?"Tutup menu":"Buka menu"}>{mobileOpen?<X/>:<Menu/>}</button></nav>
  {mobileOpen&&<div className="mobile-nav wrap" id="mobile-menu"><a href={`${APP_BASE}/`} onClick={()=>setMobileOpen(false)}><Zap size={17}/> Top Up</a><a href={`${APP_BASE}/?view=check`} onClick={()=>setMobileOpen(false)}><Search size={17}/> Cek Transaksi</a><a href={`${APP_BASE}/?view=about`} onClick={()=>setMobileOpen(false)}><Sparkles size={17}/> Tentang Project</a><a href={`${APP_BASE}/?view=faq`} onClick={()=>setMobileOpen(false)}><Headphones size={17}/> FAQ</a><button onClick={()=>{setMobileOpen(false);setLoginOpen(true)}}><User size={17}/> {userName||"Masuk Demo"}</button></div>}
  {isFaqPage&&<section className="faq-page"><div className="wrap"><button className="back-catalog" onClick={()=>window.location.href=`${APP_BASE}/`}><ArrowLeft size={17}/> Kembali ke beranda</button><div className="faq-page-head"><p className="kicker">HELP CENTER</p><h1>Ada yang mau<br/><em>ditanyakan?</em></h1><p>Temukan jawaban cepat tentang simulasi top up PixelPay.</p></div><div className="faq faq-standalone"><div className="faq-intro"><p className="kicker">FAQ</p><h2>Yang sering<br/>ditanyakan.</h2><p>Semua yang perlu kamu tahu sebelum mencoba simulasi top up PixelPay.</p></div><div className="faq-list">{[{q:"Apakah ini website top up sungguhan?",a:"Bukan. PixelPay adalah project portfolio dan seluruh transaksi di dalamnya hanya simulasi—tidak ada uang atau diamond sungguhan yang diproses."},{q:"Apakah User ID yang dimasukkan disimpan?",a:"Data akun dan riwayat transaksi demo hanya tersimpan secara lokal di browser perangkatmu, bukan dikirim ke server eksternal."},{q:"Kenapa status awalnya sedang diproses?",a:"Agar alurnya terasa realistis. Setelah beberapa detik, status demo otomatis berubah menjadi Berhasil saat kamu mengeceknya kembali."},{q:"Bisa digunakan di handphone?",a:"Bisa. Seluruh tampilan sudah dibuat responsif untuk desktop, tablet, dan layar mobile."},{q:"Bagaimana cara mengecek transaksi?",a:"Setelah membuat order demo, buka menu Cek Transaksi lalu masukkan nomor order. Kamu juga dapat memilih transaksi langsung dari daftar riwayat."}].map((item,i)=><article className={faqOpen===i?"open":""} key={item.q}><button onClick={()=>setFaqOpen(faqOpen===i?-1:i)} aria-expanded={faqOpen===i}><span>{String(i+1).padStart(2,"0")}</span><b>{item.q}</b><i>{faqOpen===i?"−":"+"}</i></button>{faqOpen===i&&<p>{item.a}</p>}</article>)}</div></div></div></section>}
  {isAboutPage&&<section className="case-study"><div className="wrap"><button className="back-catalog" onClick={()=>window.location.href=`${APP_BASE}/`}><ArrowLeft size={17}/> Kembali ke beranda</button><div className="case-hero"><div><p className="kicker">PORTFOLIO CASE STUDY · 2026</p><h1>Merancang pengalaman top up yang <em>cepat dan jelas.</em></h1><p>PixelPay adalah konsep gaming store lime-dark yang mengubah proses top up menjadi alur sederhana: pilih game, isi data, bayar, lalu pantau status transaksi.</p></div><div className="case-meta"><span>ROLE</span><b>UI/UX Designer<br/>& Front-end Developer</b><span>PROJECT TYPE</span><b>Personal Portfolio</b><span>DURATION</span><b>Concept Sprint</b></div></div><div className="case-stats"><div><strong>8</strong><span>Game tersedia</span></div><div><strong>4</strong><span>Metode pembayaran</span></div><div><strong>3</strong><span>Langkah checkout</span></div><div><strong>100%</strong><span>Responsive</span></div></div><div className="case-grid"><article><p className="kicker">01 · CHALLENGE</p><h2>Top up sering terasa ramai dan membingungkan.</h2><p>Informasi penting mudah tenggelam di antara terlalu banyak pilihan. Konsep ini memprioritaskan hierarki visual, harga transparan, dan feedback yang langsung terbaca.</p></article><article><p className="kicker">02 · APPROACH</p><h2>Satu tujuan utama di setiap layar.</h2><p>Katalog hanya untuk memilih game. Halaman detail fokus pada akun, nominal, dan pembayaran. Riwayat transaksi dipisahkan agar proses checkout tetap ringan.</p></article></div><div className="feature-showcase"><div><p className="kicker">CORE EXPERIENCE</p><h2>Dari katalog hingga order selesai.</h2><p>Seluruh interaksi dibuat sebagai prototype fungsional, bukan sekadar mockup statis.</p></div><div className="feature-list"><span><b>01</b><strong>Katalog interaktif<small>Pencarian dan pilihan game responsif</small></strong></span><span><b>02</b><strong>Checkout tervalidasi<small>ID numerik, paket, jumlah, dan pembayaran</small></strong></span><span><b>03</b><strong>Status transaksi<small>Proses bertahap dan riwayat lokal</small></strong></span><span><b>04</b><strong>Profil demo<small>Pengalaman personal tanpa backend</small></strong></span></div></div><div className="case-tech"><div><p className="kicker">TECH STACK</p><h2>Built for the web.</h2></div><div>{["Next.js","TypeScript","React","CSS","Local Storage","Responsive UI"].map(t=><span key={t}>{t}</span>)}</div></div><div className="case-cta"><p className="kicker">TRY THE PRODUCT</p><h2>Siap mencoba alurnya?</h2><p>Pilih game dan buat transaksi demo pertamamu.</p><button className="primary" onClick={()=>window.location.href=`${APP_BASE}/#games`}><Zap size={18}/> Mulai Top Up</button></div></div></section>}
  {!isGamePage&&!isCheckPage&&!isAboutPage&&!isFaqPage&&<>
  <section className="hero wrap"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/hero-lime.png`} alt="Karakter cyber orisinal dengan energi lime"/><div className="hero-glow"/><div className="hero-copy"><div className="eyebrow"><span/> TOP UP TANPA DRAMA</div><h1>LEVEL UP.<br/><em>LEBIH CEPAT.</em></h1><p>Top up game favoritmu dalam hitungan detik. Harga transparan, pembayaran aman, langsung masuk.</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById("games")?.scrollIntoView({behavior:"smooth"})}><Zap size={18} fill="currentColor"/> Top Up Sekarang</button><a href="#games">Lihat Semua Game <span>↗</span></a></div><div className="hero-stats"><div><strong>2.4M+</strong><span>Transaksi sukses</span></div><div><strong>4.9/5</strong><span>Rating pengguna</span></div><div><strong>24/7</strong><span>Customer support</span></div></div></div><div className="live-chip"><span/> 1,284 transaksi hari ini</div></section>
  <section className="trust wrap"><div><Zap/><span><b>Proses kilat</b>Saldo masuk otomatis</span></div><div><ShieldCheck/><span><b>100% aman</b>Payment terenkripsi</span></div><div><Headphones/><span><b>Support 24/7</b>Selalu siap membantu</span></div><div><Sparkles/><span><b>Harga transparan</b>Tanpa biaya tersembunyi</span></div></section>
  <section className="section wrap" id="games"><div className="section-head"><div><p className="kicker">PILIH GAME</p><h2>Game populer</h2></div></div><div className="game-grid">{shownGames.map((game,i)=><button className="game-card" onClick={()=>openGamePage(game)} aria-label={`Buka top up ${game.name}`} key={game.name} style={{"--accent":game.color} as React.CSSProperties}><div className="game-art"><span className="game-icon">{game.icon}</span><span className="game-tag">{game.tag}</span><i>{String(i+1).padStart(2,"0")}</i></div><div className="game-info"><strong>{game.name}</strong><span>{game.studio}</span></div></button>)}</div>{!query&&<button className="more" onClick={()=>setMore(!more)}>{more?"Tampilkan lebih sedikit":"Lihat semua game"} <ChevronDown size={16} className={more?"rotate":""}/></button>}{shownGames.length===0&&<div className="empty">Game “{query}” belum tersedia. Coba kata kunci lain.</div>}</section>
  </>}
  {isGamePage&&<section className="order-section detail-page" id="topup"><div className="wrap"><div className="order-heading"><button className="back-catalog" onClick={()=>window.location.href=`${APP_BASE}/#games`}><ArrowLeft size={17}/> Kembali ke katalog</button><p className="kicker">TOP UP INSTAN</p><h2>{activeGame.name}</h2><p>Pilih nominal, isi ID, lalu selesaikan pembayaran. Simulasi ini tidak memproses uang sungguhan.</p></div><div className="order-layout"><div className="steps">
   <div className="step"><Title n="01" title="Masukkan data akun" text="Pastikan ID dan server sudah benar."/><div className="input-row"><label>User ID<input inputMode="numeric" className={error&&userId.length<6?"invalid":""} value={userId} onChange={e=>setUserId(e.target.value.replace(/\D/g,"").slice(0,16))} placeholder="Contoh: 12345678"/>{error&&userId.length<6&&<small className="field-error">Minimal 6 digit angka.</small>}</label><label>Server<input inputMode="numeric" className={error&&server.length<3?"invalid":""} value={server} onChange={e=>setServer(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="Contoh: 1234"/>{error&&server.length<3&&<small className="field-error">Minimal 3 digit angka.</small>}</label></div></div>
   <div className="step"><Title n="02" title="Pilih nominal" text="Harga sudah termasuk biaya layanan."/><div className="pack-grid">{packs.map((pack,i)=><button key={pack.amount} onClick={()=>setSelectedPack(i)} className={selectedPack===i?"pack selected":"pack"}>{pack.hot&&<b className="badge">POPULER</b>}{pack.best&&<b className="badge best">HEMAT</b>}<span className="gem">◆</span><strong>{pack.amount}</strong><small>{pack.bonus}</small><em>{money(pack.price)}</em>{selectedPack===i&&<i><Check size={12}/></i>}</button>)}</div></div>
   <div className="step"><Title n="03" title="Pembayaran" text="Pilih metode yang paling nyaman."/><div className="payments">{["QRIS","GoPay","DANA","OVO"].map(p=><button onClick={()=>setPayment(p)} className={payment===p?"selected":""} key={p}><span>{p==="QRIS"?"▦":"●"}</span><b>{p}</b>{payment===p&&<Check size={15}/>}</button>)}</div></div>
  </div><aside className="summary"><div className="summary-head"><span className="mini-art">{activeGame.icon}</span><div><small>PESANANMU</small><h3>{activeGame.name}</h3></div></div><div className="summary-lines"><div><span>Item</span><b>{packs[selectedPack].amount}</b></div><div><span>Pembayaran</span><b>{payment}</b></div><div><span>Jumlah</span><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={14}/></button><b>{qty}</b><button onClick={()=>setQty(Math.min(5,qty+1))}><Plus size={14}/></button></div></div></div><div className="total"><span>Total bayar</span><strong>{money(total)}</strong></div><button className="checkout" onClick={checkout}><ShoppingBag size={18}/> Lanjutkan Pembayaran</button><p className="secure"><ShieldCheck size={14}/> Pembayaran aman & terenkripsi</p></aside></div></div></section>}
  {!isGamePage&&!isCheckPage&&!isAboutPage&&!isFaqPage&&<section className="support wrap" id="support"><div><p className="kicker">BUTUH BANTUAN?</p><h2>Party-mu tidak<br/>boleh tertunda.</h2><p>Temukan jawaban tentang simulasi transaksi, keamanan data, dan cara kerja PixelPay.</p><a className="outline support-link" href={`${APP_BASE}/?view=faq`}><Headphones size={18}/> Buka halaman FAQ</a></div><div className="quote"><div className="stars">★★★★★</div><p>“Cepat banget, belum sempat balik ke game diamond-nya sudah masuk. UI-nya juga enak dipakai.”</p><div><span>AR</span><b>Arka R.<small>Verified player</small></b></div></div></section>}
  {isCheckPage&&<section className="check-page wrap"><div className="check-shell"><button className="back-catalog" onClick={()=>window.location.href=`${APP_BASE}/`}><ArrowLeft size={17}/> Kembali ke beranda</button><p className="kicker">TRACK YOUR ORDER</p><h1>Cek transaksi.</h1><p>Masukkan nomor order yang kamu dapatkan setelah simulasi pembayaran.</p><div className="check-form"><input value={checkId} onChange={e=>setCheckId(e.target.value)} onKeyDown={e=>e.key==="Enter"&&findOrder()} placeholder="Contoh: PX-12345678"/><button className="checkout" onClick={findOrder}><Search size={17}/> Cek Status</button></div>{checkedOrder===null&&<div className="order-not-found"><AlertCircle/> Nomor order tidak ditemukan di browser ini.</div>}{checkedOrder&&<div className="status-card"><div className="status-top"><span className={checkedOrder.status==="Berhasil"?"success-icon":"processing-icon"}>{checkedOrder.status==="Berhasil"?<Check/>:<Zap/>}</span><div><small>STATUS TRANSAKSI</small><h2>{checkedOrder.status}</h2></div><b>{checkedOrder.id}</b></div><div className="status-progress"><i className="done"/><span className="done">Order dibuat</span><i className="done"/><span className="done">Pembayaran diterima</span><i className={checkedOrder.status==="Berhasil"?"done":""}/><span className={checkedOrder.status==="Berhasil"?"done":""}>Top up selesai</span></div><div className="receipt"><div><span>Game</span><b>{checkedOrder.game}</b></div><div><span>Package</span><b>{checkedOrder.package}</b></div><div><span>Player ID</span><b>{checkedOrder.playerId} <i>|</i> {checkedOrder.server}</b></div><div><span>Payment</span><b>{checkedOrder.payment}</b></div><div><span>Waktu</span><b>{checkedOrder.createdAt}</b></div><div className="receipt-total"><span>Total</span><strong>{money(checkedOrder.total)}</strong></div></div></div>}<div className="history-block"><div><p className="kicker">TERSIMPAN DI BROWSER</p><h2>Riwayat transaksi</h2></div>{history.length===0?<div className="history-empty"><ShoppingBag/>Belum ada transaksi demo.</div>:<div className="history-list">{history.map(o=><button key={o.id} onClick={()=>selectHistory(o)}><span className="history-game">{games.find(g=>g.name===o.game)?.icon||"◆"}</span><span><b>{o.game}</b><small>{o.id} · {o.createdAt}</small></span><em>{money(o.total)}<small>{Date.now()-(o.createdTs||0)>8000?"Berhasil":o.status}</small></em></button>)}</div>}</div></div></section>}
  <footer><div className="wrap footer footer-complete"><div className="footer-brand"><a className="brand" href={`${APP_BASE}/`}><span className="brand-mark"><Gamepad2 size={20}/></span><span>PIXEL<span>PAY</span></span></a><p>Top up cepat. Main lebih lama.</p><small>Project portfolio—bukan layanan transaksi sungguhan.</small></div><div className="footer-cols"><div><b>Jelajahi</b><a href={`${APP_BASE}/#games`}>Game</a><a href={`${APP_BASE}/?view=check`}>Cek Transaksi</a><a href={`${APP_BASE}/?view=about`}>Tentang Project</a></div><div><b>Bantuan</b><a href={`${APP_BASE}/?view=faq`}>FAQ</a><a href={`${APP_BASE}/?view=faq`}>Support</a><a href={`${APP_BASE}/?view=about`}>Cara kerja</a></div></div><div className="footer-bottom"><small>© 2026 PixelPay — Portfolio concept.</small><span>Made with <i>◆</i> for gamers</span></div></div></footer>
  {navigating&&<div className="page-loader" role="status" aria-live="polite"><div className="loader-logo"><Gamepad2/></div><div className="loader-ring"/><p>Menyiapkan top up</p><h2>{navigating.name}</h2><span>Mohon tunggu sebentar...</span></div>}
  {paymentOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="payment-title"><div className="payment-modal"><button className="modal-close" disabled={processingPayment} onClick={()=>setPaymentOpen(false)} aria-label="Tutup"><X/></button><p className="kicker">SIMULASI PEMBAYARAN</p><h2 id="payment-title">Selesaikan pembayaran.</h2><p>Bayar sebelum waktu simulasi berakhir. Tidak ada uang sungguhan yang diproses.</p><div className="payment-code"><span>{payment}</span><b>{money(total)}</b><small>KODE DEMO · PIXELPAY</small></div><div className="payment-detail"><span>Game</span><b>{activeGame.name}</b><span>Package</span><b>{packs[selectedPack].amount}</b></div><button className={`checkout simulate-pay ${processingPayment?"is-loading":""}`} disabled={processingPayment} onClick={completePayment}>{processingPayment?<><span className="button-spinner"/> Memproses Pembayaran...</>:<><Zap size={18}/> Simulasikan Pembayaran Berhasil</>}</button>{processingPayment&&<p className="processing-note">Sedang memverifikasi transaksi demo. Jangan tutup halaman.</p>}</div></div>}
  {error&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="error-title"><div className="alert-modal"><button className="modal-close" onClick={()=>setError(false)} aria-label="Tutup"><X/></button><span className="alert-icon"><AlertCircle/></span><p className="kicker">DATA BELUM LENGKAP</p><h2 id="error-title">Lengkapi data akunmu.</h2><p>User ID dan Server wajib diisi sebelum melanjutkan pembayaran.</p><button className="checkout" onClick={()=>setError(false)}>Lengkapi Sekarang</button></div></div>}
  {success&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="success-title"><div className="success-modal"><button className="modal-close" onClick={()=>setSuccess(false)} aria-label="Tutup"><X/></button><span className="success-icon"><Check/></span><p className="kicker">ORDER CREATED</p><h2 id="success-title">Pesanan sedang diproses.</h2><p>Pembayaran demo diterima. Status otomatis berubah menjadi berhasil setelah beberapa detik.</p><div className="order-id"><span>NOMOR ORDER</span><strong>{orderId}</strong><button aria-label="Salin nomor order" onClick={()=>navigator.clipboard?.writeText(orderId)}><Copy size={16}/></button></div><div className="receipt"><div><span>Game</span><b>{activeGame.name}</b></div><div><span>Package</span><b>{packs[selectedPack].amount}</b></div><div><span>Player ID</span><b>{userId} <i>|</i> {server}</b></div><div><span>Payment</span><b>{payment}</b></div><div className="receipt-total"><span>Total</span><strong>{money(total)}</strong></div></div><div className="modal-actions"><button className="new-order" onClick={resetOrder}>Transaksi Baru</button><button className="checkout" onClick={()=>window.location.href=`${APP_BASE}/?view=check`}>Cek Transaksi</button></div></div></div>}
  {loginOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="login-title"><div className="alert-modal profile-modal"><button className="modal-close" onClick={()=>setLoginOpen(false)} aria-label="Tutup"><X/></button><span className="profile-avatar"><User/></span>{userName?<><p className="kicker">AKUN DEMO</p><h2 id="login-title">Halo, {userName}!</h2><p>Profil ini tersimpan lokal di browser untuk kebutuhan demo portfolio.</p><button className="new-order logout" onClick={()=>{localStorage.removeItem("pixelpay_user");setUserName("");setLoginName("");setLoginOpen(false)}}>Keluar dari akun demo</button></>:<><p className="kicker">LOGIN DEMO</p><h2 id="login-title">Kenalan dulu, yuk.</h2><p>Masukkan nama untuk membuat profil demo. Tidak perlu password.</p><input className="profile-input" autoFocus value={loginName} onChange={e=>setLoginName(e.target.value.slice(0,24))} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Nama kamu"/><button className="checkout" onClick={login}>Masuk Demo</button></>}</div></div>}
 </main>
}
function Title({n,title,text}:{n:string,title:string,text:string}){return <div className="step-title"><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
